# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# Set up the ssh keys
# Volumes don't get passed into docker, so we use /workspace/root:
# https://stackoverflow.com/questions/64213744/google-cloud-build-using-volumes-on-dockerfile
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    mkdir -p /workspace/root/.ssh
    echo "$$SSH_KEY" >> /workspace/root/.ssh/id_rsa
    chmod 400 /workspace/root/.ssh/id_rsa
    cp known_hosts.github /workspace/root/.ssh/known_hosts

# Do the build
- name: 'docker:stable'
  args: [
    'build', '.',
    '-t', 'gcr.io/$PROJECT_ID/build_engine',
  ]

images: [
  'gcr.io/$PROJECT_ID/build_engine',
]

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-bot-ssh/versions/latest
    env: 'SSH_KEY'