# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
# Do the build
- name: 'docker:stable'
  args: [
    'build', '.',
    '-t', 'gcr.io/$PROJECT_ID/build_engine',
  ]
images: [
  'gcr.io/$PROJECT_ID/build_engine',
]